### ISSUE TITLE
Please update compatibility string to 3.10/3.12

### ISSUE THREAD

**Issue by mattdm** [lomegor/Remove-Accessibility#6]
Please update for 3.10 and 3.12. On my high-resolutions screen, I like to have the fonts larger than the assumed DPI. (In fact, I want them set to the _actual_ DPI.) In order to do this, I set the Scaling Factor in gnome-tweak-tool, which apparently enables Accessibility and makes the icon show, even though I don't want to change any of these options once I've set them.

No actual changes appear necessary — just update the versions in metadata.json. Thank you!

**Comment by mariospr** [comment]
Updating the metadata.json file will make it work but if you're playing with the text-scaling-factor value then you need to enable this extension **after** having set that value.

This happens because the extension only hides the icon at the time of enabling so, if you modify the text-scaling-factor to anything bigger than 1.00 afterwards, it will be considered as that the "Larger Text" a11y option is enabled and the icon will show up again.

I placed a pull request today to fix this, by monitoring the icon visibility and not ever letting it show up while the extension is enabled, which also updates the metadata.json file. See it here:
https://github.com/lomegor/Remove-Accessibility/pull/7

Now waiting for it to be reviewed...

**Comment by mariospr** [comment]
Btw, @mattdm. You seem to have the very same use case than me about setting the text scaling factor, so I thought you might find this other extension I just wrote interesting:

https://extensions.gnome.org/extension/1018/text-scaler
